# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
- name: Setting config parameters
  hosts: cloud
  connection: local
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - "./../../../../cello/src/agent/ansible/vars/{{ env }}.yml"
    - "./../../vars/{{ pteenv }}.yml"
  tasks:
    - include_tasks: "common/{{ mode }}.yml"

- name: Launching PTE ADMIN
  hosts: cloud
  connection: local
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - "./../../../../cello/src/agent/ansible/vars/{{ env }}.yml"
    - "./../../vars/{{ pteenv }}.yml"
  tasks:
    - include_tasks: "admin/tasks/{{ mode }}.yml"
  tags: "pteadmin"

- name: Launching PTE CLIENT
  hosts: cloud
  connection: local
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - "./../../../../cello/src/agent/ansible/vars/{{ env }}.yml"
    - "./../../vars/{{ pteenv }}.yml"
  tasks:
    - include_tasks: "client/tasks/{{ mode }}.yml"
  tags: "pteclient"
