# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
- name: Stop PTE admin pod
  command: "./kubectl --kubeconfig='kubeconfig' delete -f ../../../../../tools/ATD/vars/{{ pteenv }}/pte-admin-{{ pteenv }}-{{ chaincode | replace('_', '') }}-k8s.yml"
  args:
    chdir: "{{ playbook_dir }}/../../../../cello/src/agent/ansible/vars/"
  tags: "pteadmindown"

- name: Check the status of secret for pulling images
  command: >-
    ./kubectl --kubeconfig='kubeconfig' get secrets -o=custom-columns=NAME:.metadata.name
    regcred
  args:
    chdir: "{{ playbook_dir }}/../../../../cello/src/agent/ansible/vars/"
  ignore_errors: yes
  register: "secretstatus"
  when: >
    pte.repo.username | default("") | length > 0 and
    pte.repo.password | default("") | length > 0

- name: Delete secret for image
  command: >-
    ./kubectl --kubeconfig kubeconfig delete secrets regcred
  args:
    chdir: "{{ playbook_dir }}/../../../../cello/src/agent/ansible/vars/"
  register: "secretdelete"
  when: >
    pte.repo.username | default("") | length > 0 and
    pte.repo.password | default("") | length > 0 and
    secretstatus.rc == 0

- name: Delete configMap
  command: >-
    ./kubectl --kubeconfig kubeconfig delete configmap admin{{ pteenv }}{{ chaincode | replace('_', '') }}
  args:
    chdir: "{{ playbook_dir }}/../../../../cello/src/agent/ansible/vars/"
  tags: "config"
