version: '2'

services:
  server:
    container_name: server
    image: nexus3.hyperledger.org:10001/hyperledger/fabric-testviewer:1.2.0
    tty: true
    working_dir: /code/server
    command: node index.js
    ports:
      - 3000:3000

  app:
    container_name: app
    image: nexus3.hyperledger.org:10001/hyperledger/fabric-testviewer:1.2.0
    tty: true
    working_dir: /code/app
    command: node_modules/.bin/ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    depends_on:
      - server
