apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fabricreport
spec:
  selector:
    matchLabels:
      app: fabricreport
  replicas: 1
  template:
    metadata:
      labels:
        app: fabricreport
    spec:
      containers:
      - name: server
        image: nexus3.hyperledger.org:10001/hyperledger/fabric-testviewer:1.2.0
        workingDir: /code/server
        command: ["node", "index.js"]
        ports:
          - containerPort: 3000
      - name: app
        image: nexus3.hyperledger.org:10001/hyperledger/fabric-testviewer:1.2.0
        workingDir: /code/app
        command: ["./node_modules/.bin/ng", "serve", "--host", "0.0.0.0"]
        ports:
          - containerPort: 4200