apiVersion: v1
kind: Service
metadata:
  labels:
    app: fabricreport
  name: reportservice
spec:
  ports:
  - name: port-1
    nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2
    nodePort: 31000
    port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app: fabricreport
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}