version: '2'

services:

  composer0:
    image: hyperledger/composer-playground:latest
    ports:
      - "7050:8080"
    command: pm2-docker composer-playground
    depends_on:
       - orderer0
       - peer0
#       - couchdb0
    volumes:
        - ${COMPOSER0_PATH_TO_HFC}:/home/composer/.hfc-key-store
        - /var/hyperledger/bddtests/volumes/composer:/var/hyperledger/bddtests/volumes/composer

    environment:
        -  COMPOSER_CONFIG=${COMPOSER0_COMPOSER_CONFIG}
        -  DEBUG=*

#          COMPOSER_CONFIG: >
#            {
#              "connectionProfiles": {
#                "hlfabric": {
#                   "type": "hlfv1",
#                   "orderers": [
#                      "url": "grpcs://orderer0:7050",
#                      "cert": "./systestv1/tls/orderer/ca-cert.pem",
#                      "hostnameOverride": "orderer0"
#                   ],
#                   "ca": "http://peer0:7054",
#                   "peers": [
#                      {
#                         "requestURL": "grpcs://peer0:7051",
#                         "eventURL": "grpcs://peer0:7053",
#                         "cert": "./systestv1/tls/peers/peer0/ca-cert.pem",
#                      }
#                   ],
#                   "channel": "com.acme.blockchain.jdoe.Channel1",
#                   "mspID": "peerOrg0",
#                   "deployWaitTime": "300",
#                   "invokeWaitTime": "100",
#                   "keyValStore": "keyValStoreV1"
#                }
#              },
#              "credentials": {
#                "hlfabric": {
#                  "admin": "Xurw3yU9zI0l"
#                }
#              }
#            }

  composer1:
    image: hyperledger/composer-playground:latest
    ports:
      - "7051:8080"
    command: pm2-docker composer-playground
    depends_on:
       - orderer0
       - peer2
#       - couchdb2
    volumes:
        - /var/hyperledger/bddtests/volumes/composer:/var/hyperledger/bddtests/volumes/composer
    environment:
          COMPOSER_CONFIG: ${COMPOSER1_COMPOSER_CONFIG}
