# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
- name: Setup variables
  set_fact:
    testdir: "{{ playbook_dir }}/../../vars/{{ pteenv }}/CITest"

- name: testcase
  set_fact:
    testcase: "{{ testcase | default('multihost') }}"

- name: testcase_query
  set_fact:
    testcase_query: "{{ testcase_query | default('multihost_query') }}"

- name: Make sure that pte config directory is removed
  file:
    path: "{{ testdir }}"
    state: absent
  tags: "ptedir"
